[UPower]

# Holo: Disable CriticalPowerAction
#
# The responsibility for the equivalent action when out of battery charge is
# taken by a combination of vpower and SteamUI, when it dips below 0.5% (at the
# time of writing), and it gives a 10 second margin for SteamUI to close.
AllowRiskyCriticalPowerAction=yes
CriticalPowerAction=Ignore
