#  SPDX-License-Identifier: LGPL-2.1+
#
#  Copyright © 2023 Valve Corporation.
#
#  This is required to avoid some connectivity failures in ICMP-blocking scenarios
#  See https://github.com/ValveSoftware/SteamOS/issues/1006

net.ipv4.tcp_mtu_probing = 1
