[General]
DisplayServer=wayland
InputMethod=qtvirtualkeyboard

[Theme]
Current=breeze

[Autologin]
Relogin=true
Session=gamescope-wayland.desktop
User=deck

[X11]
DisplayCommand=/usr/lib/holo/holo-rotate-x11-screen
# Janky workaround for wayland sessions not stopping in sddm, kills
# all active sddm-helper sessions on teardown
DisplayStopCommand=/usr/bin/gamescope-wayland-teardown-workaround
